galaxy_info:
  author: Aerogear
  description: Clone and install the Mobile Control Panel for Openshift

  issue_tracker_url: https://github.com/aerogear/mobile-core/issues

  license: license (MIT)

  min_ansible_version: 2.2

  platforms:
  - name: macOS
    versions:
    - all
  - name: OSX
    versions:
    - all
  - name: Fedora
    versions:
    - 26
    - 25

  galaxy_tags:
  - aerogear
  - openshift
  - mobile
  - control
  - panel
  - mcp

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
