---
# tasks file for create-mobile-client-crd

- name: Copy CRD definition to tmp file
  template:
    src: ../files/mobile-client-crd.yaml
    dest: /tmp/mobile-client-crd.yaml  

- name: Create mobileClient CRD
  shell: "oc create -f /tmp/mobile-client-crd.yaml"

- block:
  - name: Get admin clusterrole
    shell: "oc get clusterrole admin -o yaml"
    register: admin_original_content

  - name: Create new admin clusterrole file
    template:
      src: ../files/clusterrole-template.j2
      dest: /tmp/clusterrole.yaml
    vars:
      original_content: "{{ admin_original_content.stdout | from_yaml | to_nice_yaml (indent=2) }}"

  - name: Remove timestamp from admin
    lineinfile:
      path: /tmp/clusterrole.yaml
      regexp: "creationTimestamp:"
      state: absent

  - name: Replace admin clusterrole
    shell: "oc replace -f /tmp/clusterrole.yaml"

- block:
  - name: Get edit clusterrole
    shell: "oc get clusterrole admin -o yaml"
    register: edit_original_content

  - name: Create new edit clusterrole file
    template:
      src: ../files/clusterrole-template.j2
      dest: /tmp/clusterrole.yaml
    vars:
      original_content: "{{ edit_original_content.stdout | from_yaml | to_nice_yaml (indent=2) }}"

  - name: Remove timestamp from edit
    lineinfile:
      path: /tmp/clusterrole.yaml
      regexp: "creationTimestamp:"
      state: absent

  - name: Replace edit clusterrole
    shell: "oc replace -f /tmp/clusterrole.yaml"
